// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoACaF0-4TdxHBDcZU5KcsvSjBjrPq_Ds',
    appId: '1:164555710817:web:bdafb3254b186fc4356520',
    messagingSenderId: '164555710817',
    projectId: 'crud-e14a7',
    authDomain: 'crud-e14a7.firebaseapp.com',
    storageBucket: 'crud-e14a7.appspot.com',
    measurementId: 'G-W3EWBRL77F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6tnEuHIOcDteMdeI3cFuMezSPR2fqJ8',
    appId: '1:164555710817:android:371d5fb540ae2c1c356520',
    messagingSenderId: '164555710817',
    projectId: 'crud-e14a7',
    storageBucket: 'crud-e14a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmELYFd5IwX5szcV6pGvEo816h7dits8',
    appId: '1:164555710817:ios:95b782e6dfd710f9356520',
    messagingSenderId: '164555710817',
    projectId: 'crud-e14a7',
    storageBucket: 'crud-e14a7.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdmELYFd5IwX5szcV6pGvEo816h7dits8',
    appId: '1:164555710817:ios:95b782e6dfd710f9356520',
    messagingSenderId: '164555710817',
    projectId: 'crud-e14a7',
    storageBucket: 'crud-e14a7.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoACaF0-4TdxHBDcZU5KcsvSjBjrPq_Ds',
    appId: '1:164555710817:web:c32d53bb0ea95b22356520',
    messagingSenderId: '164555710817',
    projectId: 'crud-e14a7',
    authDomain: 'crud-e14a7.firebaseapp.com',
    storageBucket: 'crud-e14a7.appspot.com',
    measurementId: 'G-YXPLY3HSV0',
  );
}
